# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faeaa29232f5e59982b422a56cd11944b289430114c945c8a59044469364195a8c8025a328fe887f3530db804d7afe634a8c32d363675929fc48e1caa77abbd5

test:
  secret_key_base: fae7fd5f3063e1562869b4ecb493ff189e76128251440613ab675adc163a68f44f8bfcebebd332f1d5ac5ceecce84259e14712c6335872b550333e44e83394e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
